function [EE,GG,CC] = RefineEquAReal0(p1, p2, P1_w, W2, solution,tT)




    pn1 = [p1 p2(:,5:8)];
    pn2 = [p2 p2(:,6:8) p2(:,5)];


    n_nc = xcross_mat(pn1,pn2);
    ne_c = xnorm(n_nc);

    Pn1_w = [P1_w W2(:,5:8)];
    Pn2_w = [W2 W2(:,6:8) W2(:,5)];
    
    neLine = length(Pn1_w);
    

    Q=zeros(2*neLine,48);
    N=zeros(2*neLine,3);
    
    for i = 1:12
        nx=ne_c(1,i); ny=ne_c(2,i); nz=ne_c(3,i);
        Px=Pn1_w(1,i); Py=Pn1_w(2,i); Pz=Pn1_w(3,i);    
        if i <=8
            Q(i,1:10)=[Px.*nx+Py.*ny+Pz.*nz,...    %1
              2*Py.*nz-2*Pz.*ny,...       %s1
              2*Pz.*nx-2*Px.*nz,...       %s2
              2*Px.*ny-2*Py.*nx,...       %s3
              Px.*nx-Py.*ny-Pz.*nz,...     %s1^2
              2.*Px.*ny+2*Py.*nx,...      %s1*s2
              2.*Px.*nz+2*Pz.*nx,...       %s1*s3
              Py.*ny-Px.*nx-Pz.*nz,...     %s2^2
              2*Py.*nz+2*Pz.*ny,...       %s2*s3
              Pz.*nz-Px.*nx-Py.*ny,...     %s3^2
             ];
        elseif i == 9
            Q(i,1:18)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        elseif i == 10
            Q(i,1:26)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              0,0,0,0,0,0,0,0,ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny]; 
        elseif i == 11
            Q(i,1:34)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        elseif i == 12
            Q(i,1:42)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        end
    end
    for j = 1:12
        nx=ne_c(1,j); ny=ne_c(2,j); nz=ne_c(3,j);
        Px=Pn2_w(1,j); Py=Pn2_w(2,j); Pz=Pn2_w(3,j);
        if j <=4
             Q(j+12,1:10)=[Px.*nx+Py.*ny+Pz.*nz,...    %1
              2*Py.*nz-2*Pz.*ny,...       %s1
              2*Pz.*nx-2*Px.*nz,...       %s2
              2*Px.*ny-2*Py.*nx,...       %s3
              Px.*nx-Py.*ny-Pz.*nz,...     %s1^2
              2.*Px.*ny+2*Py.*nx,...      %s1*s2
              2.*Px.*nz+2*Pz.*nx,...       %s1*s3
              Py.*ny-Px.*nx-Pz.*nz,...     %s2^2
              2*Py.*nz+2*Pz.*ny,...       %s2*s3
              Pz.*nz-Px.*nx-Py.*ny,...     %s3^2
             ];
        elseif j == 5 || j ==12
              Q(j+12,1:18)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        elseif j == 6 || j == 9
              Q(j+12,1:26)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              0,0,0,0,0,0,0,0,ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        elseif j == 7 || j == 10
            Q(j+12,1:34)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        elseif j == 8 || j == 11
             Q(j+12,1:42)=[Px.*nx+Pz.*nz,...
              -2*Pz.*ny,...
              2*Pz.*nx-2*Px.*nz,...
              2*Px.*ny,...
              Px.*nx-Pz.*nz,...
              2.*Px.*ny,...
              2.*Px.*nz+2*Pz.*nx,...
              -Px.*nx-Pz.*nz,...
              2*Pz.*ny,...
              Pz.*nz-Px.*nx,...
              0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ny,2*nz,-2*nx,-ny,2*nx,ny,2*nz,-ny];
        end
    end

    
%     for i = 1:22
%         nx=ne_c(1,i); ny=ne_c(2,i); nz=ne_c(3,i);
%         Px=Pn1_w(1,i); Py=Pn1_w(2,i); Pz=Pn1_w(3,i);
%         Q(i,1:10)=[Px.*nx+Py.*ny+Pz.*nz,...    %1
%               2*Py.*nz-2*Pz.*ny,...       %s1
%               2*Pz.*nx-2*Px.*nz,...       %s2
%               2*Px.*ny-2*Py.*nx,...       %s3
%               Px.*nx-Py.*ny-Pz.*nz,...     %s1^2
%               2.*Px.*ny+2*Py.*nx,...      %s1*s2
%               2.*Px.*nz+2*Pz.*nx,...       %s1*s3
%               Py.*ny-Px.*nx-Pz.*nz,...     %s2^2
%               2*Py.*nz+2*Pz.*ny,...       %s2*s3
%               Pz.*nz-Px.*nx-Py.*ny,...     %s3^2
%              ];
%     end
%     
%     for i = 22:28
%         nx=ne_c(1,i); ny=ne_c(2,i); nz=ne_c(3,i);
%         if i >= 23 && i <= 25
%             Px=Pn1_w(1,i); Py=Pn1_w(2,i);
%             Q(i,1:18)=[Px.*nx+Py.*ny,...
%               2*Py.*nz,...
%               -2*Px.*nz,...
%               2*Px.*ny-2*Py.*nx,...
%               Px.*nx-Py.*ny,...
%               2.*Px.*ny+2*Py.*nx,...
%               2.*Px.*nz,...
%               Py.*ny-Px.*nx,...
%               2*Py.*nz,...
%               -Px.*nx-Py.*ny,...
%               nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         elseif i >= 26 && i <= 27
%             Px=Pn1_w(1,i); Py=Pn1_w(2,i);
%             Q(i,1:26)=[Px.*nx+Py.*ny,...
%               2*Py.*nz,...
%               -2*Px.*nz,...
%               2*Px.*ny-2*Py.*nx,...
%               Px.*nx-Py.*ny,...
%               2.*Px.*ny+2*Py.*nx,...
%               2.*Px.*nz,...
%               Py.*ny-Px.*nx,...
%               2*Py.*nz,...
%               -Px.*nx-Py.*ny,...
%               0,0,0,0,0,0,0,0,nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         elseif i == 28
%             Px=Pn1_w(1,i); Py=Pn1_w(2,i);
%             Q(i,1:34)=[Px.*nx+Py.*ny,...
%               2*Py.*nz,...
%               -2*Px.*nz,...
%               2*Px.*ny-2*Py.*nx,...
%               Px.*nx-Py.*ny,...
%               2.*Px.*ny+2*Py.*nx,...
%               2.*Px.*nz,...
%               Py.*ny-Px.*nx,...
%               2*Py.*nz,...
%               -Px.*nx-Py.*ny,...
%               0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         end
%     end  
%     
%     
%     for j = 1:28
%         nx=ne_c(1,j); ny=ne_c(2,j); nz=ne_c(3,j);
%         if j>=1 && j<=3 || j == 8 || j == 9 || j == 14
%              Px=Pn2_w(1,j); Py=Pn2_w(2,j); Pz=Pn2_w(3,j);
%              Q(j+28,1:10)=[Px.*nx+Py.*ny+Pz.*nz,...    %1
%                   2*Py.*nz-2*Pz.*ny,...       %s1
%                   2*Pz.*nx-2*Px.*nz,...       %s2
%                   2*Px.*ny-2*Py.*nx,...       %s3
%                   Px.*nx-Py.*ny-Pz.*nz,...     %s1^2
%                   2.*Px.*ny+2*Py.*nx,...      %s1*s2
%                   2.*Px.*nz+2*Pz.*nx,...       %s1*s3
%                   Py.*ny-Px.*nx-Pz.*nz,...     %s2^2
%                   2*Py.*nz+2*Pz.*ny,...       %s2*s3
%                   Pz.*nz-Px.*nx-Py.*ny,...     %s3^2
%                  ];
%         end
%         if j==4 || j==10 || j==15 || j==19
%              Px=Pn2_w(1,j); Py=Pn2_w(2,j);
%               Q(j+28,1:18)=[Px.*nx+Py.*ny,...
%                   2*Py.*nz,...
%                   -2*Px.*nz,...
%                   2*Px.*ny-2*Py.*nx,...
%                   Px.*nx-Py.*ny,...
%                   2.*Px.*ny+2*Py.*nx,...
%                   2.*Px.*nz,...
%                   Py.*ny-Px.*nx,...
%                   2*Py.*nz,...
%                   -Px.*nx-Py.*ny,...
%                   nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         end
%         if j==5 || j==11 || j==16 || j==20 || j==23
%              Px=Pn2_w(1,j); Py=Pn2_w(2,j);
%               Q(j+28,1:26)=[Px.*nx+Py.*ny,...
%               2*Py.*nz,...
%               -2*Px.*nz,...
%               2*Px.*ny-2*Py.*nx,...
%               Px.*nx-Py.*ny,...
%               2.*Px.*ny+2*Py.*nx,...
%               2.*Px.*nz,...
%               Py.*ny-Px.*nx,...
%               2*Py.*nz,...
%               -Px.*nx-Py.*ny,...
%               0,0,0,0,0,0,0,0,nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         end
%         if j==6 || j==12 || j==17 || j==21 || j==24 || j==26 
%              Px=Pn2_w(1,j); Py=Pn2_w(2,j);
%              Q(j+28,1:34)=[Px.*nx+Py.*ny,...
%               2*Py.*nz,...
%               -2*Px.*nz,...
%               2*Px.*ny-2*Py.*nx,...
%               Px.*nx-Py.*ny,...
%               2.*Px.*ny+2*Py.*nx,...
%               2.*Px.*nz,...
%               Py.*ny-Px.*nx,...
%               2*Py.*nz,...
%               -Px.*nx-Py.*ny,...
%               0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         end
%         if j==7 || j==13 || j==18 || j==22 || j==25 || j==27 || j==28 
%              Px=Pn2_w(1,j); Py=Pn2_w(2,j);
%              Q(j+28,1:42)=[Px.*nx+Py.*ny,...
%               2*Py.*nz,...
%               -2*Px.*nz,...
%               2*Px.*ny-2*Py.*nx,...
%               Px.*nx-Py.*ny,...
%               2.*Px.*ny+2*Py.*nx,...
%               2.*Px.*nz,...
%               Py.*ny-Px.*nx,...
%               2*Py.*nz,...
%               -Px.*nx-Py.*ny,...
%               0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,nz,-2*ny,2*nx,-nz,2*nx,-nz,2*ny,nz];
%         end
%     end
%     


    N(1:neLine,:)=-ne_c.';
    N(neLine+1:2*neLine,:)=-ne_c.';


    if abs(det(N.'*N)) < 2e-10
        CC=(pinv(N.'*N)*N.')*Q;
    else
        CC=((N.'*N)\N.')*Q;
    end

    EE=Q-N*CC;


    EE(2*neLine+1,:) = [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0];
    EE(2*neLine+2,:) = [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0];
    EE(2*neLine+3,:) = [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0];
    EE(2*neLine+4,:) = [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0];
    EE(2*neLine+5,:) = [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0];
    EE(2*neLine+6,:) = [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1];
  

    GG=EE.'*EE;
    
end
